plugins {
    id 'java'
    id 'maven-publish'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

var jUnitVersion = "5.9.1"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:${jUnitVersion}')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'com.google.guava:guava:32.0.1-jre'

    //Map Struct 라이브러리
    implementation 'org.mapstruct:mapstruct:1.5.3.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.3.Final'
}

test {
    useJUnitPlatform()
}

javadoc{
    exclude("org/example/Main.java")
}